### Testing routes
GET http://localhost:3000/notifications

### Sending notification
POST http://localhost:3000/notifications/create
Content-Type: application/json

{
    "content": "New Message",
    "category": "New Category",
    "recipientId": "dfdfsdfs"
}